import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;


public class Home extends JFrame {

	public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PasswordLbl = new java.awt.Label();
        TalkIcon = new javax.swing.JLabel();
        getStartedBtn = new java.awt.Button();
        userTextField = new java.awt.TextField();
        passwordTextField = new java.awt.TextField();
        UsernameLbl = new java.awt.Label();
        loginBtn = new java.awt.Button();
        WhiteBackGround = new javax.swing.JLabel();
        GardensByTheBayBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        setBounds(300,300,600,400);
        PasswordLbl.setBackground(new java.awt.Color(255, 255, 255));
        PasswordLbl.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        PasswordLbl.setText("Password");
        getContentPane().add(PasswordLbl);
        PasswordLbl.setBounds(210, 390, 120, 30);

        TalkIcon.setBackground(new java.awt.Color(255, 255, 255));
        TalkIcon.setForeground(new java.awt.Color(255, 255, 255));
        TalkIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/talk teus.png"))); // NOI18N
        getContentPane().add(TalkIcon);
        TalkIcon.setBounds(300, 100, 190, 200);

        getStartedBtn.setBackground(new java.awt.Color(255, 255, 255));
        getStartedBtn.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getStartedBtn.setForeground(new java.awt.Color(255, 0, 0));
        getStartedBtn.setLabel("Register");
        getContentPane().add(getStartedBtn);
        getStartedBtn.setBounds(210, 520, 360, 50);

        userTextField.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(userTextField);
        userTextField.setBounds(360, 390, 200, 30);

        passwordTextField.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(passwordTextField);
        passwordTextField.setBounds(360, 350, 200, 30);

        UsernameLbl.setBackground(new java.awt.Color(255, 255, 255));
        UsernameLbl.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        UsernameLbl.setText("Username");
        getContentPane().add(UsernameLbl);
        UsernameLbl.setBounds(210, 350, 120, 30);

        loginBtn.setBackground(new java.awt.Color(255, 0, 0));
        loginBtn.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setLabel("Login");
        getContentPane().add(loginBtn);
        loginBtn.setBounds(210, 460, 360, 50);

        WhiteBackGround.setBackground(new java.awt.Color(255, 255, 255));
        WhiteBackGround.setForeground(new java.awt.Color(255, 255, 255));
        WhiteBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WhiteBackground.PNG"))); // NOI18N
        WhiteBackGround.setText("White");
        getContentPane().add(WhiteBackGround);
        WhiteBackGround.setBounds(200, 320, 390, 260);

        GardensByTheBayBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Singapore Garden City.jpg"))); // NOI18N
        GardensByTheBayBG.setText("jLabel1");
        getContentPane().add(GardensByTheBayBG);
        GardensByTheBayBG.setBounds(-1, 0, 2240, 1000);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GardensByTheBayBG;
    private java.awt.Label PasswordLbl;
    private javax.swing.JLabel TalkIcon;
    private java.awt.Label UsernameLbl;
    private javax.swing.JLabel WhiteBackGround;
    private java.awt.Button getStartedBtn;
    private java.awt.Button loginBtn;
    private java.awt.TextField passwordTextField;
    private java.awt.TextField userTextField;

}
